services:
    tollkit:
        build: .
        ports:
            - 8080:80 #host:docker
        volumes:
            #  allows you to make changes to your application code on the host machine and have those changes reflected inside the container
            - .:/var/www/toolkit #map the current directory on host where the docker-compose.yml file is located: to the specified docker container
        depends_on:
            - mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "mysql"] # Example health check for MySQL
            interval: 10s # Check health every 10 seconds
            timeout: 5s # Maximum time to wait for the command to complete
            retries: 3 # Retry up to 3 times before considering unhealthy
    mysql:
        image: mysql
        env_file:
            - .env ## This references the .env file in the same directory
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        env_file:
            - .env
        depends_on:
            - mysql
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081/"] # Replace with actual host if needed
            interval: 10s
            timeout: 5s
            retries: 3
